name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Checkout submodules
      uses: snickerbockers/submodules-init@v4
 
    - name: Install Lua/LuaJIT
      uses: leafo/gh-actions-lua@v9.1.0
      with:
        luaVersion: 5.4
  
    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v4.3.0
      with:
        luaRocksVersion: 3.9.0
       
    - name: Install dependencies
      shell: bash
      run: |
        sudo ./luarocks install fennel
        fennel --version
      
    - name: Run build
      run: make
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: love-api.fnl
